accounts/urls.py
from django.urls import path
from .views import *

app_name = 'accounts'

urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login'),
    path('register/', UserRegisterView.as_view(), name='signup'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('profile/<slug:slug>', ProfileDetailView.as_view(), name='profile'),
    path('edit/', ProfileUpdateView.as_view(), name='edit'),
]

api/urls.py
from django.urls import path
from .views import *

app_name = 'api'

urlpatterns = [
    path('', APIData.as_view(), name='api'),
]

blog/urls.py
from django.urls import path
from .views import *

app_name = 'blog'

urlpatterns = [
    path('', Blog.as_view(), name='blog'),
    path('add_article/', AddArticle.as_view(), name='add_article'),
    path('<slug:slug>/', ArticleDetail.as_view(), name='article'),
]

clndr/urls.py
from django.urls import path, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('blog/', include('blog.urls')),
    path('api/', include('api.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from accounts.models import Profile

class Article(models.Model):
    header = models.CharField(max_length=255)
    content = models.TextField()
    author_id = models.ForeignKey(User, on_delete=models.CASCADE)
    slug = models.SlugField()
    date = models.DateTimeField(auto_now_add=True)
    views = models.IntegerField(default = 0)

    def __str__(self):
        return self.header
    
    def get_absolute_url(self):
        return f'/{self.slug}'
    
    class Meta:
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'


class Comment(models.Model):
    content = models.TextField()
    author_id = models.ForeignKey(Profile, on_delete=models.CASCADE)
    article_id = models.ForeignKey('Article', on_delete=models.CASCADE, null=True)
    comment_id = models.ForeignKey('Comment', on_delete=models.CASCADE, null=True)
    date = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return f'Comment by {self.author_id} on {self.date}'
    
    class Meta:
        verbose_name = 'Комент'
        verbose_name_plural = 'Коменты'

blog/forms.py
from django import forms

from blog.models import Article, Comment

class AddArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ('header', 'content')

class AddCommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content', )
    
    def __init__(self, *args, **kwargs):
        
        try:
            self.request = kwargs.pop("request")
        except:
            pass
        super().__init__(*args, **kwargs)
        self.fields['content'].widget.attrs = {"placeholder": 'Comment'}

blog/views.py
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, CreateView, FormView, View
from django.views.generic.detail import SingleObjectMixin
from .models import Article as A, Profile
from .forms import *
from main.utils import DataMixin
from django.db.models import F
from django.template.defaultfilters import slugify
from django.contrib.auth.mixins import LoginRequiredMixin

class Blog(DataMixin, ListView):
    model = A
    template_name = 'blog/blog.html'

    def get_context_data(self, **kwargs):
        queryset = self.get_queryset()
        articles_by_views = queryset.order_by('-date')
        articles_by_time = queryset
        context = super().get_context_data(**kwargs)
        c_def = self.get_data(title = 'Blog', articles_by_views = articles_by_views, articles_by_time = articles_by_time)
        return context | c_def

class Article(DataMixin, DetailView):
    model = A
    template_name = 'blog/article.html'
    context_object_name = 'article'

    def get(self, request, *args, **kwargs):
        article = self.get_object()
        article.views = F('views') + 1
        article.save()
        return super().get(request, *args, **kwargs)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_data(title = context['article'].header)
        return context | c_def
    
class ArticleDetail(View):
    def get(self, request, *args, **kwargs):
        view = ArticleDisplay.as_view()
        return view(request, *args, **kwargs)
    
    def post(self, request, *args, **kwargs):
        view = ArticleComment.as_view()
        return view(request, *args, **kwargs)

class ArticleDisplay(DataMixin, DetailView):
    model = A
    template_name = 'blog/article.html'
    context_object_name = 'article'

    def get(self, request, *args, **kwargs):
        article = self.get_object()
        article.views = F('views') + 1
        article.save()
        return super().get(request, *args, **kwargs)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        comment_list = Comment.objects.filter(article_id = context['article']).order_by('-date')
        form = AddCommentForm()
        c_def = self.get_data(comment_list = comment_list, form = form)
        return c_def | context

    # model = Article
    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     title = context['article'].title
    #     comment_list = Comment.objects.filter(article = context['article']).order_by('-date')
    #     category_list = context['article'].category.all()
    #     form = AddCommentForm()
    #     c_def = self.get_data(title = title, comment_list = comment_list,
    #                            category_list = category_list, form = form)
    #       return c_def | context
    
class ArticleComment(SingleObjectMixin, FormView):
    model = A
    form_class = AddCommentForm
    template_name = 'blog/article.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().post(request, *args, **kwargs)
    
    def get_form_kwargs(self):
        kwargs = super(ArticleComment, self).get_form_kwargs()
        kwargs['request'] = self.request
        return kwargs
    
    def form_valid(self, form):
        comment = form.save(commit = False)
        post = self.get_object()
        comment.post = self.object
        comment.article_id = A.objects.get(slug = post.slug)
        comment.author_id = Profile.objects.get(user = self.request.user) 
        comment.save()
        return super().form_valid(form)
    
    def get_success_url(self):
        post = self.get_object()
        return reverse('blog:article', kwargs = {'slug': post.slug})

class AddArticle(LoginRequiredMixin, DataMixin, CreateView):
    model = A
    form_class = AddArticleForm
    template_name = 'blog/add_article.html'
    success_url = reverse_lazy('blog:blog')

    def get_unique_slug(self, fields):
        slug = slugify(fields.header)
        slug_number = 0
        sorted_articles = A.objects.filter(slug__contains = slug)
        for article in sorted_articles:
            try:
                if article.slug == slug + '-' + article.slug[len(slug) + 1] or article.slug == slug:
                    slug_number += 1
                    
            except IndexError:
                if article.slug == slug:
                    slug_number += 1
        return slug + '-' + str(slug_number) if slug_number > 0 else slug

    def form_valid(self, form):
        article = form.save(commit = False)
        article.author_id = self.request.user
        article.slug = self.get_unique_slug(article)
        article.save()
        return super().form_valid(form)
        
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_data(title = 'Add Article')
        return context | c_def

blog/templates/blog/add_article.html
{% extends 'main/base.html' %}

{% block content %}
<h1>Add new article</h1>
<form action="" method="post">
    {% csrf_token %}
    {{ form }}
    <button class="btn waves-effect" type="submit">Create article</button>
</form>
{% endblock %}

blog/templates/blog/article.html
{% extends 'main/base.html' %}

{% block content %}
<h1>{{ article.header }}</h1>
<div class="additional">
    <div>
        <a href="{% url 'accounts:profile' article.author_id %}">{{ article.author_id }}</a>
    </div>
    <div>
        {{ article.date|timesince }} 
    </div>
</div>
<div class="content">
    {{ article.content }}
</div>
<div class="additional">
    {{ article.views }} views
</div>
<h3>Comments</h3>
{% if is_auth %}
<form action="" method="post">
    {% csrf_token %}
    {% for f in form %}
        {{ f }}
    {% endfor %}
    <button class="btn waves-effect">Send</button>
</form>
{% endif %}
{% for c in comment_list %}
    <div class="comment">
        <div class="additional">
            <div>{{ c.author_id }}</div>
            <div>{{ c.date|timesince }} ago</div>
        </div>
       <p>{{ c.content }}</p>
    </div>
{% endfor %}
{% endblock %}

blog/templates/blog/blog.html
{% extends 'main/base.html' %}
{% load static %}

{% block content %}
{% if is_auth %}
<p>
  <a href="{% url 'blog:add_article' %}">Add new article</a>
</p>
{% endif %}

<p>
  <span>Sort by:</span>
  <span id="time" class="radio checked">Time</span>
  <span id="views" class="radio">Views</span>
</p>
<div id="articles-by-time">
  {% for a in articles_by_time %}
      <h1><a href="{% url 'blog:article' a.slug %}">{{ a.header }}</a></h1>
      <div class="additional">
        <a href="{% url 'accounts:profile' a.author_id %}">{{ a.author_id }}</a>
      </div>
      <p>{{ a.content }}</p>
  {% endfor %}
</div>
<div id="articles-by-views">
  {% for a in articles_by_views %}
      <h1><a href="{% url 'blog:article' a.slug %}">{{ a.header }}</a></h1>
      <div class="additional">
        <a href="{% url 'accounts:profile' a.author_id %}">{{ a.author_id }}</a>
      </div>
      <p>{{ a.content }}</p>
  {% endfor %}  
</div>
<script src="{% static 'blog/js/sort.js' %}"></script>
{% endblock %}