accounts/urls.py
from django.urls import path
from .views import *

app_name = 'accounts'

urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login'),
    path('register/', UserRegisterView.as_view(), name='signup'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('profile/<slug:slug>', ProfileDetailView.as_view(), name='profile'),
    path('edit/', ProfileUpdateView.as_view(), name='edit'),
]

api/urls.py
from django.urls import path
from .views import *

app_name = 'api'

urlpatterns = [
    path('', APIData.as_view(), name='api'),
]

blog/urls.py
from django.urls import path
from .views import *

app_name = 'blog'

urlpatterns = [
    path('', Blog.as_view(), name='blog'),
    path('add_article/', AddArticle.as_view(), name='add_article'),
    path('<slug:slug>/', ArticleDetail.as_view(), name='article'),
]

clndr/urls.py
from django.urls import path, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('blog/', include('blog.urls')),
    path('api/', include('api.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from .views import *
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('', Index.as_view(), name='home'),
    path('month/<int:y>/<int:m>', Month.as_view(), name='month'),
]

main/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import View
from django.views.generic.base import TemplateView
from django.views.generic import CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.views import LoginView, LogoutView
from django.http import JsonResponse
from .utils import DataMixin
from .models import *
from .forms import *
import requests
import asyncio
import aiohttp

class Index(DataMixin, TemplateView):
    template_name='main/index.html'
    
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        c_def = self.get_data(title = 'Homepage')
        return context | c_def
    
    def get(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)
        y = context['y']
        m = context['m']

        url = f'http://127.0.0.1:8000/api/?y={y}&m={m}'

        async def fetch_data(url):
            async with aiohttp.ClientSession() as session:
                async with session.get(url) as response:
                    data = await response.json()
                    return data

        async def main():
            api_data = await fetch_data(url)
            days = api_data.get('days')
            context['year_month'] = api_data.get('title')
            for week in days:
                for day in week:
                    if day.get('number') == context['d']:
                        context['today'] = day
                        break

        asyncio.run(main()) 

        return self.render_to_response(context)
    
class Month(DataMixin, TemplateView):
    template_name = 'main/month.html'

    def get(self, request, *args, **kwargs):
        
        context = self.get_context_data(**kwargs)
        y = kwargs['y']
        m = kwargs['m']

        url = f'http://127.0.0.1:8000/api/?y={y}&m={m}'

        async def fetch_data(url):
            async with aiohttp.ClientSession() as session:
                async with session.get(url) as response:
                    data = await response.json()
                    return data

        async def main():
            context['api_data'] = await fetch_data(url)
            context['title'] = context['api_data'].get('title')

        asyncio.run(main()) 
        
        return self.render_to_response(context)

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        c_def = self.get_data(title = 'title')
        return context | c_def

main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link rel="stylesheet" href="{% static 'main/css/style.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=PT+Sans+Caption:wght@400;700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Alice&family=PT+Sans+Caption:wght@400;700&display=swap" rel="stylesheet">
    <title>{{ title }}</title>
</head>
<body>
    <nav>
        <div class="nav-wrapper">
            <a href="{% url 'home' %}" class="brand-logo">sowing calendar</a>
            <ul id="nav-mobile" class="right hide-on-med-and-down">
                <li>
                    <a href="{% url 'blog:blog' %}">blog</a>
                </li>
                {% if is_auth %}
                    <li>
                        <a href="{% url 'accounts:profile' user.username %}">{{ user.username }}</a>
                    </li>
                    <li>
                        <a href="{% url 'accounts:logout' %}">logout</a>
                    </li>
                {% else %}
                  <li>
                    <a href="{% url 'accounts:signup' %}">sign up</a>
                  </li>
                  <li>
                    <a href="{% url 'accounts:login' %}">log in</a>
                  </li>
                {% endif %}
              </ul>
        </div>
    </nav>
    <div class="main">
        {% block content %}

        {% endblock %}    
    </div>
</body>
</html>

main/templates/main/index.html
{% extends 'main/base.html' %}

{% block content %}

<p>Today is the {{ year_month }}, {{ today.number }} — <a href="{% url 'month' y m %}">current month</a></p>
<p>Sign: {{ today.sign.symbol }}, {{ today.sign.word }}</p>
<p>Phase: {{ today.phase.symbol }}, {{ today.phase.word }}</p>
<p>Recomendation: {{ today.recomendations }}</p>
    <p>
        A sowing calendar is a valuable tool for gardeners and farmers that provides guidance on the optimal time to sow different types of plants,
        vegetables, and flowers. It takes into account factors like climate, soil conditions, and the specific requirements of each plant to ensure
        successful germination and growth.
    </p>
    <p>
        How to use the sowing calendar:
    </p>
    <ul>
        <li>
            Determine your location: The first step is to identify your geographical location. This is crucial as different regions have varying climates and growing seasons. Knowing your location will help you find accurate information tailored to your specific area.
        </li>
        <li>
            Choose your plants: Once you know your location, select the plants you want to grow. Whether it's vegetables, herbs, or flowers, each plant has its own ideal sowing time. Our sowing calendar provides detailed information on when and how to sow each type of plant.
        </li>
        <li>
            Find the recommended sowing dates: Using our user-friendly interface, navigate to the sowing calendar section and enter your location details. Our smart algorithm will generate a customized calendar based on your location, indicating the best times to sow each plant.
        </li>
        <li>
            Follow the instructions: Once you have the sowing dates, follow the instructions provided for each plant. This may include tips on soil preparation, seed treatment, and planting techniques. Our comprehensive guides will help you make the most of your sowing calendar.
        </li>
        <li>
            Track your progress: Keep a record of your sowing activities and monitor the growth of your plants. This will help you evaluate the effectiveness of the sowing calendar and make adjustments for future seasons.
        </li>
    </ul>
    <p>
        Remember, the sowing calendar is a valuable tool, but it's essential to consider other factors like local weather conditions and specific plant requirements. Adaptation and experimentation are key to successful gardening.
    </p>
    <p>
        Start using our sowing calendar today and unlock the full potential of your garden! Happy sowing!
    </p>
{% endblock %}

main/templates/main/month.html
{% extends 'main/base.html' %}

{% block content %}
<h1>{{ api_data.title }}</h1>
<div class="table">
  <div class="tr">
    <div class="td">M</div>
    <div class="td">T</div>
    <div class="td">W</div>
    <div class="td">T</div>
    <div class="td">F</div>
    <div class="td">S</div>
    <div class="td">S</div>
  </div>
  {% for week in api_data.days %}
  <div class="tr">
    {% for day in week %}
      <div class="td">
        {{ day.number }}
        <span>{{ day.sign.symbol }}</span>
        <span>{{ day.phase.symbol }}</span>
      </div>
    {% endfor %}
    </div>
  {% endfor %}
</div>
{% for week in api_data.days %}
  {% for day in week %}
    <p><b>{{ day.number }}</b> {{ day.recomendations }}</p>
  {% endfor %}
{% endfor %}
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
</script>
{% endblock %}